In [1]:
from numpy.random import randint
import time
import numpy as np

num = 200

A = randint(0,10,size=(num,num))
B = randint(0,10,size=(num,num))

start_time = time.time()
C_1 = A@B
stop_time = time.time()
time_used = stop_time - start_time
print(f"Time used: {time_used}")
print(C_1)

C_2 = np.zeros((num,num))
start_time = time.time()
for i in range(num):
    for j in range(num):
        for k in range(num):
            C_2[i,j] += A[i,k]*B[k,j]
time_used = time.time() - start_time
print(f"Time used: {time_used}")
print(C_2)



Time used: 0.011896371841430664
[[3859 4102 4039 ... 4094 4051 4036]
 [3767 4183 4138 ... 4026 3990 4018]
 [4032 4075 4172 ... 4355 3943 4162]
 ...
 [4091 4175 4437 ... 4319 4299 4240]
 [4182 4405 4393 ... 4494 4443 4493]
 [3990 4247 4308 ... 4335 4308 4276]]
Time used: 3.834149122238159
[[3859. 4102. 4039. ... 4094. 4051. 4036.]
 [3767. 4183. 4138. ... 4026. 3990. 4018.]
 [4032. 4075. 4172. ... 4355. 3943. 4162.]
 ...
 [4091. 4175. 4437. ... 4319. 4299. 4240.]
 [4182. 4405. 4393. ... 4494. 4443. 4493.]
 [3990. 4247. 4308. ... 4335. 4308. 4276.]]


In [2]:
even_numbers = [x for x in range(1,11) if x % 2 == 0]
print(even_numbers)

[2, 4, 6, 8, 10]
