In [1]:
from numpy.random import randint
import time
import numpy as np

num = 200

A = randint(0,10,size=(num,num))
B = randint(0,10,size=(num,num))

start_time = time.time()
C_1 = A@B
stop_time = time.time()
time_used = stop_time - start_time
print(f"Time used: {time_used}")
print(C_1)

C_2 = np.zeros((num,num))
start_time = time.time()
for i in range(num):
    for j in range(num):
        for k in range(num):
            C_2[i,j] += A[i,k]*B[k,j]
time_used = time.time() - start_time
print(f"Time used: {time_used}")
print(C_2)

Time used: 0.011523723602294922
[[4051 3932 4224 ... 3958 3993 4346]
 [3988 4386 4012 ... 4369 4035 4577]
 [4056 3981 3941 ... 4098 3770 4192]
 ...
 [3919 3823 4102 ... 4080 3777 4257]
 [3956 3988 4129 ... 3896 4198 4394]
 [3848 3781 3910 ... 4185 3455 4320]]
Time used: 3.9271903038024902
[[4051. 3932. 4224. ... 3958. 3993. 4346.]
 [3988. 4386. 4012. ... 4369. 4035. 4577.]
 [4056. 3981. 3941. ... 4098. 3770. 4192.]
 ...
 [3919. 3823. 4102. ... 4080. 3777. 4257.]
 [3956. 3988. 4129. ... 3896. 4198. 4394.]
 [3848. 3781. 3910. ... 4185. 3455. 4320.]]
