In [2]:
import numpy as np
A = np.array([[1,2,10,20],
              [3,4,30,40]])
B = np.array([[1,3],
              [2,4],
              [10,30],
              [20,40]])
C = A@B
D = B@A
print(C)
print(D)

[[ 505 1111]
 [1111 2525]]
[[  10   14  100  140]
 [  14   20  140  200]
 [ 100  140 1000 1400]
 [ 140  200 1400 2000]]
