In [1]:
import numpy as np
A = np.array([[1,2,10,20],
              [3,4,30,40]])
B = np.array([[1,3],
              [2,4],
              [10,30],
              [20,40]])
C = A@B
D = B@A
print(C)
print(D)

from numpy.random import randint
import time
num = 200
A = randint(0,10,size=(num,num))
B = randint(0,10,size=(num,num))
start_time = time.time()
C_1 = A@B
end_time = time.time()
print(f"seconds: {end_time-start_time}")

C = np.zeros((num,num))
start_time = time.time()
for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            C[i,j] += A[i,k]*B[k,j]
end_time = time.time()
print(f"seconds: {end_time-start_time}")

[[ 505 1111]
 [1111 2525]]
[[  10   14  100  140]
 [  14   20  140  200]
 [ 100  140 1000 1400]
 [ 140  200 1400 2000]]
seconds: 0.005558013916015625
seconds: 4.904746055603027
